init_model/27494 relationship
awesome-academy/oe35_fels pull request #3
Opened 2020-08-19 09:47 UTC by tranduythuat

ready

2020-08-19 14:02 UTC, tranduythuat commented
ready

2020-08-19 14:03 UTC, phuongsai requested changes
Code chưa OK cần fix lại cho hợp lí.

2020-08-19 14:03 UTC, phuongsai commented on app/Models/Social.php
> +    ];
```suggestion
    'user_id',
    ];
```

2020-08-19 14:03 UTC, phuongsai commented on app/Models/Question.php
> +        'update_at'
```suggestion

```

2020-08-19 16:10 UTC, tranduythuat commented
ready

fixed

2020-08-20 01:01 UTC, merged

2020-08-20 01:15 UTC, phuongsai commented on app/Models/User.php
> +    public function socials()
Chưa fix theo "Naming Conventions" #3